visualisation of the navbar
WildCodeSchool/orleans-0919-php-toilettage pull request #12
Opened 2019-10-24 15:52 UTC by MathiasBln

this is just the visualisation of the navbar, next time i will change the logo and make all the options

2019-10-24 16:25 UTC, Olivier-Jamet approved these changes

2019-10-24 19:29 UTC, sblondeau requested changes

2019-10-24 19:29 UTC, sblondeau commented on public/assets/css/style.css
> +    border: solid 1px #fc5b4c;
les couleurs en variables css svp

2019-10-24 19:29 UTC, sblondeau commented on src/View/Home/include/navbar.html.twig
> +                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
non! celle liste sera dynamique car elle viendra de la liste des chiens entrés en BDD, il ne faut donc pas écrire de noms de chiens "en dur" ici car ça sera à enlever plus tard sinon.

2019-10-25 08:33 UTC, Toua45 approved these changes

2019-10-25 08:46 UTC, sblondeau requested changes

2019-10-25 08:46 UTC, sblondeau commented on src/View/Home/include/navbar.html.twig
> +            <li class="nav-item active">
la classe active doit etre mise dynamiquement pour indiquer le lien actuellement "cliqué", si tu la laisses ici le lien "Le  Salon" sera tjs mis en avant, quelque soit la page. Retire le active et le `<span class="sr-only">(current)</span>` pour le moment

2019-10-25 08:46 UTC, sblondeau commented on public/assets/css/style.css
> +    box-shadow: 0px 5px 5px grey;
grey devrait etre une variable CSS
--shadow-color est possible par ex

2019-10-25 08:57 UTC, Toua45 approved these changes

2019-10-25 09:01 UTC, sblondeau approved these changes

2019-10-25 15:04 UTC, merged