S01 us06 formulaire contact
WildCodeSchool/orleans-0919-php-toilettage pull request #13
Opened 2019-10-24 16:09 UTC by Toua45

2019-10-24 16:28 UTC, Olivier-Jamet approved these changes

2019-10-24 19:41 UTC, sblondeau requested changes

2019-10-24 19:41 UTC, sblondeau commented on public/assets/css/style.css
> +    background-color: #f5f9fa;
couleurs en variables css

pas d'id dans le CSS, utilise des classes !

2019-10-24 19:41 UTC, sblondeau commented on src/View/Home/Include/_form.html.twig
> +    <section id="contact">
comme écrit plus haut, je veux des class, pas des id
ça fonctionne mais les id c'est pour le JS, les ancres ou autre, pour le CSS c'est des classes ;-)

2019-10-24 19:41 UTC, sblondeau commented on src/View/Home/Include/_form.html.twig
> +                    <input type="password" class="form-control" id="inputPassword4" placeholder="John">
attention aux copier/coller...
tu as un type=password et un id inputpassword4 alors que c'est un champ "prénom"

2019-10-24 19:41 UTC, sblondeau commented on src/View/Home/Include/_form.html.twig
> +                <img src="https://i.postimg.cc/BnXBQK0Q/patte-de-chien.png" alt="dog-paw" class="dog-paw">
si tu mets une image, elle doit etre stockée en local, pas en ligne

2019-10-24 19:41 UTC, sblondeau commented on src/View/Home/Include/_form.html.twig
> +                <label for="exampleFormControlSelect1"></label>
tes for/id doivent avoir un nom comprehensible, ici "subject" par ex

2019-10-25 08:28 UTC, AlexandreCln requested changes

2019-10-25 08:28 UTC, AlexandreCln commented on src/View/Home/Include/_form.html.twig
> +                    <input type="text" class="form-control" id="lastname" placeholder="Doe" required>
Tes input doivent avoir un name=""

2019-10-25 08:32 UTC, AlexandreCln approved these changes

2019-10-25 08:48 UTC, sblondeau approved these changes

2019-10-25 08:48 UTC, sblondeau commented on src/Controller/HomeController.php
>  namespace App\Controller;
je ne devrais pas voir ce fichier dans cette PR normalement...

2019-10-25 08:48 UTC, merged