Add blocAdress and footer
WildCodeSchool/orleans-0919-php-toilettage pull request #25
Opened 2019-11-04 08:31 UTC by Olivier-Jamet

Add blocAdress and the footer blocs to the homepage.

2019-11-04 08:34 UTC, AlexandreCln commented on public/assets/css/style.css
> +    box-shadow: 0 5px 5px var(--backgroundColor);
Tu doit mettre 0px au lieu de 0

2019-11-04 08:38 UTC, AlexandreCln commented on src/View/Home/Include/_blocAdress.html.twig
> +                    <p class="pCoordonnate">195, rue des Chimoutons</p>
Les classes se répètent, utilise la div parent

2019-11-04 08:38 UTC, AlexandreCln commented on public/assets/css/style.css
> +.pCoordonnate {
.card-header p {}

2019-11-04 08:39 UTC, AlexandreCln commented on public/assets/css/style.css
> +/*.container_map {
Code mort, à supprimmer

2019-11-04 08:40 UTC, AlexandreCln commented on public/assets/css/style.css
> +    /*font-size: 2em;*/
Code mort à supprimmer

2019-11-04 08:48 UTC, AlexandreCln commented on src/View/Home/Include/_blocAdress.html.twig
> +        <div class="row justify-content-evenly blockCoordonnate" >
Mettre justify-content-evenly plutot dans le CSS vu qu'il y à dejà du style sur la classe blockCoordonnate ?

2019-11-04 08:51 UTC, AlexandreCln commented on public/assets/css/style.css
> +a:focus {
Toutes les lignes CSS d'en dessous sont vides, il est inutile de les appeler du coup

2019-11-04 08:53 UTC, AlexandreCln commented on src/View/Home/Include/_footer.html.twig
> +<div class="container-fluid" >
Il manque une balise footer

2019-11-04 08:55 UTC, AlexandreCln requested changes
.

2019-11-05 03:08 UTC, Olivier-Jamet commented on public/assets/css/style.css
> +    box-shadow: 0 5px 5px var(--backgroundColor);
Si je mets 0px, on a un warning "redundant"! En fait 0 ce doit être 0, px ou autre chose c'est 0!

2019-11-05 22:06 UTC, sblondeau commented
c'est encore une fois sur MASTER et non sur DEV, je ne relis pas (mais on perd du temps !)
et j'attends tjs mon gâteau !

2019-11-06 12:33 UTC, closed without merging