So2 us6 home
WildCodeSchool/orleans-0919-php-toilettage pull request #28
Opened 2019-11-06 07:51 UTC by Olivier-Jamet

add Blocs adress, map and footer;

2019-11-06 13:32 UTC, sblondeau requested changes

2019-11-06 13:32 UTC, sblondeau commented on public/assets/css/style.css
> +    background-color: #ffffff;
couleur en variable css

2019-11-06 13:32 UTC, sblondeau commented on public/assets/css/style.css
> +    background-color: black;
idem

2019-11-06 13:32 UTC, sblondeau commented on public/assets/css/style.css
> +    color: white;
idem

2019-11-06 13:32 UTC, sblondeau commented on public/assets/css/style.css
> +    color: white;
encore

2019-11-06 13:32 UTC, sblondeau commented on public/assets/css/style.css
> +    color: #ffffff;
là aussi

2019-11-06 13:32 UTC, sblondeau commented on src/View/Home/Include/_blocAdress.html.twig
> +                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2672.9946047892004!2d1.8728976152127994!3d47.93648807312474!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e4
le client exige openstreetmap et non google map ! ;-)

2019-11-06 13:32 UTC, sblondeau commented on src/View/Home/Include/_blocAdress.html.twig
> +                    <div class="card-header who">Adresse</div>
utilise la balise address au lieu d'un div, c'est sémantiquement mieux

2019-11-07 11:18 UTC, AlexandreCln requested changes

2019-11-07 11:18 UTC, AlexandreCln commented on public/assets/css/style.css
> +    color: #000000;
Utilise une variable couleur

2019-11-07 11:18 UTC, AlexandreCln commented on src/View/Home/Include/_footer.html.twig
> +                <div><p><a href="">Partenaires</a></p></div>
le doute m'habite

2019-11-07 14:06 UTC, AlexandreCln requested changes

2019-11-07 14:06 UTC, AlexandreCln commented on src/View/Home/Include/_blocAdress.html.twig
> +                    <div class="card-header who">Adresse</div>
oubli de changer la balise en adress

2019-11-08 08:01 UTC, AlexandreCln approved these changes

2019-11-08 12:47 UTC, sblondeau approved these changes

2019-11-08 12:48 UTC, merged