pages mentiosn légales finies avec css
WildCodeSchool/orleans-0919-php-toilettage pull request #31
Opened 2019-11-06 15:56 UTC by bcarme

2019-11-06 16:04 UTC, AlexandreCln requested changes

2019-11-06 16:04 UTC, AlexandreCln commented on public/assets/css/style.css
>      color: black;
Variable de couleur

2019-11-06 16:04 UTC, AlexandreCln commented on src/View/Success/success.html.twig
> +<<!doctype html>
Supprimer cette page

2019-11-07 13:56 UTC, bcarme commented on src/View/Success/success.html.twig
> +<<!doctype html>
C'est fait

2019-11-07 13:56 UTC, bcarme commented on public/assets/css/style.css
>      color: black;
c'est changé

2019-11-07 15:57 UTC, closed without merging