secured form displaying errors or success message
WildCodeSchool/orleans-0919-php-toilettage pull request #32
Opened 2019-11-07 12:12 UTC by bcarme

2019-11-07 15:47 UTC, AlexandreCln requested changes

2019-11-07 15:47 UTC, AlexandreCln commented on src/Controller/HomeController.php
> +                    $error['mail'] = "Format invalide d'email";
il manque un 's'

2019-11-07 15:53 UTC, AlexandreCln approved these changes

2019-11-07 21:56 UTC, sblondeau requested changes

2019-11-07 21:56 UTC, sblondeau commented on src/Controller/HomeController.php
> +            if (empty($data['firstname'])) {
bien, mais il vous manque la verif des longueurs max sur lastname, firstname et mail

2019-11-07 21:56 UTC, sblondeau commented on src/Controller/HomeController.php
> +                return $this->twig->render('Home/index.html.twig', [
non
si tout s'est bien passé et que error est empty, tu ne fais pas un render, sinon tu ne "vide" pas ton POST (et pb si tu réactualises). Il faut que tu faire une redirection via header Location (et dans une future US, tu pourras ajouter l'envoie du mail juste avant)

tu enlèves le return, la méthode revoie donc :void, tu peux aussi la passer en private

et depuis index, tu appelle la méthode $this->send(), en gardant le render de index et en lui passant success éventuellement.

sinon quand tu vas rajouter d'autres choses dans index(), tu seras obligé de dupliquer dans send() ce qui n'est pas bien. On en discute si c'est pas clair

2019-11-08 15:51 UTC, Toua45 approved these changes

2019-11-08 16:42 UTC, sblondeau requested changes

2019-11-08 16:42 UTC, sblondeau commented on public/assets/css/style.css
>      background-color: var(--mainColor) !important;
doublement non
déjà pas de !important dans vos CSS svp
et ensuite ce n'est pas btn que tu dois surcharger, mais éventuellement .btn-primary ?

2019-11-11 15:18 UTC, Toua45 approved these changes

2019-11-11 20:52 UTC, sblondeau requested changes
ne passe pas travis

2019-11-12 09:48 UTC, AlexandreCln approved these changes

2019-11-12 14:21 UTC, sblondeau approved these changes

2019-11-12 14:21 UTC, merged