modification css of the navbar
WildCodeSchool/orleans-0919-php-toilettage pull request #50
Opened 2019-11-13 08:30 UTC by MathiasBln

modification of the css in the navbar

2019-11-13 12:59 UTC, sblondeau requested changes

2019-11-13 12:59 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $races = $homeManager->selectAll();
je pense qu'on a le meme pb ici sur les races. Il faut un RaceManager pour une entity race, pas de HomeManager, tu n'as pas d'entity "Home"
Je te laisse voir avec Barbara, je lui ai déjà expliqué

2019-11-13 12:59 UTC, sblondeau commented on src/Model/HomeManager.php
> +class HomeManager extends AbstractManager
fichier inutile

2019-11-13 17:13 UTC, bcarme commented
Il reste deux couleurs en dur sur le bouton FB

2019-11-14 08:29 UTC, bcarme approved these changes

2019-11-14 10:00 UTC, sblondeau approved these changes

2019-11-14 10:00 UTC, merged