footer retrieved and split css file
WildCodeSchool/orleans-0919-php-toilettage pull request #57
Opened 2019-11-14 17:05 UTC by bcarme

2019-11-14 19:19 UTC, sblondeau requested changes

2019-11-14 19:19 UTC, sblondeau commented on src/View/Home/Include/_footer.html.twig
> +                   class="fa fa-facebook"> <img src="../../../../assets/images/fb-logo-white.png"></a>
hum... src="assets/images/fb-logo-white.png" devrait etre le bon chemin, car tu pars du dossier public où ton serveur est lancé.

2019-11-14 20:41 UTC, bcarme commented on src/View/Home/Include/_footer.html.twig
> +                   class="fa fa-facebook"> <img src="../../../../assets/images/fb-logo-white.png"></a>
ok corrigé

2019-11-15 08:30 UTC, sblondeau approved these changes

2019-11-15 08:30 UTC, merged