Sprint 3 Pricelist page
WildCodeSchool/orleans-0919-php-toilettage pull request #63
Opened 2019-11-15 15:49 UTC by AlexandreCln

2019-11-15 15:55 UTC, bcarme requested changes
white color mettre variable

2019-11-15 16:01 UTC, bcarme approved these changes

2019-11-15 16:32 UTC, sblondeau requested changes

2019-11-15 16:32 UTC, sblondeau commented on src/Controller/PricelistController.php
> +            $straighteningPrice = $race['price'] + 50;
c'est tjs 50€ de plus ? pour toutes les races ?
dans ce cas créé une constante au moins

2019-11-15 16:48 UTC, bcarme approved these changes

2019-11-15 20:16 UTC, sblondeau approved these changes

2019-11-16 15:32 UTC, bcarme approved these changes

2019-11-16 18:04 UTC, merged