S04 13 menu conseil
WildCodeSchool/orleans-0919-php-toilettage pull request #73
Opened 2019-11-17 14:22 UTC by bcarme

2019-11-17 17:05 UTC, AlexandreCln approved these changes

2019-11-17 20:44 UTC, sblondeau requested changes

2019-11-17 20:44 UTC, sblondeau commented on src/Controller/AdviceController.php
> +        $animalManager = new RaceManager();
tu instancies 2 fois RaceManager ?

2019-11-18 11:56 UTC, bcarme commented on src/Controller/AdviceController.php
> +        $animalManager = new RaceManager();
C'est le code d'Alex, pour attribuer une autre méthode à une autre variable pour effectuer ensuite la boucle foreach ?

2019-11-18 12:29 UTC, AlexandreCln commented on src/Controller/AdviceController.php
> +        $animalManager = new RaceManager();
C'est parce que tu as collé mon code après le tien, ou tu avais dejà instancié un RaceManager. Supprime juste le deuxième

2019-11-18 13:23 UTC, AlexandreCln approved these changes

2019-11-18 14:49 UTC, sblondeau approved these changes

2019-11-18 14:49 UTC, merged